name = "Gunji SMP"
version = "2.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccad3f7e3aba5d2aeff100f6c76a1c4b3da4197c665efb60ae0fef5e86ff1ecb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"
