name = "Gunji SMP"
version = "2.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7acbf046d9c0e31fc822757ff9f8d0234eea6fbdac3fe9631bbdb3a141f3ed1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"
