name = "Gunji SMP"
version = "2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9133e0ac14b8d4088afe8dfc8499a5e7d4ca4df2d0c0dc094dbae76d0836a9a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"
