name = "Gunji SMP"
version = "2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a6baebb03ea96df0ee8a89ea73f357458359e2e0337c8632d0f034d521c9cd6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.186"
